import React from "react";

const PaymentForm = ({ formData = {}, handleChange }) => {
  return (
    <form className="grid grid-cols-2 gap-6 mt-4">
      <div>
        <label className="block font-medium">Client Name:</label>
        <input type="text" name="clientName" value={formData.clientName || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Project Name:</label>
        <input type="text" name="projectName" value={formData.projectName || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
       <div>
        <label className="block font-medium">Address:</label>
        <input type="text" name="Address" value={formData.Address || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Technology:</label>
        <input type="text" name="technology" value={formData.technology || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Milestone:</label>
        <input type="text" name="milestone" value={formData.milestone || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Duration From:</label>
        <input type="date" name="duration.from" value={formData.duration?.from || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Duration To:</label>
        <input type="date" name="duration.to" value={formData.duration?.to || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Amount:</label>
        <input type="number" name="amount" value={formData.amount || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Discount:</label>
        <input type="number" name="discount" value={formData.discount || ""} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div>
        <label className="block font-medium">Currency:</label>
        <select name="currency" value={formData.currency || "USD"} onChange={handleChange} className="w-full border rounded p-2" required>
          <option value="USD">USD</option>
          <option value="EUR">EUR</option>
          <option value="INR">INR</option>
        </select>
      </div>
      <div>
        <label className="block font-medium">Invoice Generated By:</label>
        <input type="text" name="generatedBy" value={formData.generatedBy} onChange={handleChange} className="w-full border rounded p-2" required />
      </div>
      <div className="col-span-2 flex items-center gap-2">
        <input type="checkbox" name="isRecurring" checked={formData.isRecurring || false} onChange={handleChange} />
        <label className="font-medium">Recurring Payment?</label>
      </div>
    </form>
  );
};

export default PaymentForm;

